### ISSUE TITLE
Deprecated selectors

### ISSUE THREAD

**Issue by slipperypenguin** [varemenos/duotone-denim-syntax#1]
Currently, Atom performs automatic translation of selectors, but this feature will be removed in a few release cycles to minimize startup time.

Depreciation message:
"Starting from Atom v1.13.0, the contents of atom-text-editor elements are no longer encapsulated within a shadow DOM boundary. This means you should stop using `:host` and `::shadow` pseudo-selectors, and prepend all your syntax selectors with `syntax--`. "

**Comment by varemenos** [comment]
v0.4.3 should fix this, thank you for reporting this issue.
